baseURL: "https://benzeitlin1010.netlify.app"
languageCode: "en-us"
title: "Benjamin Zeitlin's Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Benjamin Zeitlin's Profile"
  description: "Welcome to my professional website, showcasing my skills, work experience, and projects."
  favicon: "/fav.png"

  useBootstrapCDN: false
  mathjax: false
  animate: true

  theme:
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left

  navbar:
    align: ms-auto
    brandName: "Benjamin Zeitlin"
    disableSearch: false
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  hero:
    enable: true
    intro: "Hello! My name is"
    title: "Benjamin Zeitlin"
    subtitle: "I believe preparation and patience is key to success"
    content: "I'm an extroverted individual with a passion in all things data. I specialize in Data Analysis, Machine Learning, and Mathematical Modeling."
    image: /images/hero.jpg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1VKTvFQ6mFA3eNdG6QVk4MENHrZ8nfPvR/view?usp=drive_link"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/benjaminzeitlin1010
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/benjamin-zeitlin-81856a22a/
      customIcons:
        - icon: /fav.png
          url: "mailto:benzeitlin1010@gmail.com"

  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |
      I am currently taking a pause on my Masters in Computer Science at Virginia Tech to pursue a career. I plan to attend my masters in the coming year. I received my Bachelors of Science in Computational Modeling and Data Analytics in May 2024, where I then pursued my Masters starting in June 2024 until December 2024. I specialize in data analysis, software development, and database management. I am passionate about leveraging technology to solve complex challenges. I have experience working on projects in various fields, including biostatistics, web development, and environmental data analysis. I hope to pursue a career in helping people with my data analytic skills in a non-profit manner.

      Skills:
      - Python, Java, C, MATLAB, R, SQL, CUDA, Typescript, Javascript
      - Data Visualization: PowerBI, Tableau, RShiny, Pandas, Dplyr, Tidyverse
      - Software Development: GitHub, GitLab, Linux, Visual Studio Code, Anaconda
      - Database Tools: Oracle Systems, SQL, PLSQL, TSQL, Postgres, Microsoft Azure

  experience:
    enable: true
    items:
      - job: "Data Science Undergraduate Researcher"
        company: "Virginia Tech Center for Biostatistics and Health Data Science"
        companyUrl: "https://biostat.centers.vt.edu"
        date: "April 2023 - May 2024"
        content: |
          - Compiled statistical reports in R and Python for an introductory biostatistics research program to underrepresented communities sponsored by the NIH, iThrive, and AbbVie.
          - Produced ANOVA tables and PCA analyses for data preparation, cleaning, and visualizations of clientele data.

      - job: "Computing Consultant"
        company: "Virginia Tech Academy of Data Science"
        companyUrl: "https://data.science.vt.edu"
        date: "January 2024 - May 2024"
        content: |
          - Advised clients on data analysis, gathering, and experimental design using Bayesian methods in R and Python.

      - job: "Student Web Developer"
        company: "Virginia Tech Academy of Integrated Science"
        companyUrl: "https://www.ais.science.vt.edu"
        date: "March 2023 - April 2024"
        content: |
          - Designed, deployed, and maintained a comprehensive website for managing information related to multiple majors and minors.

      - job: "Computer Science Undergraduate Teaching Assistant"
        company: "Virginia Tech College of Engineering"
        companyUrl: "https://eng.vt.edu"
        date: "August 2022 - May 2023"
        content: |
          - Substitute Instructor for an Introductory Python course with 90+ students, covering programming fundamentals, OOP, and search algorithms using Python Jupyter.
          - Assisted 400+ students 3 days a week in help sessions on sorting algorithms and dictionaries.

  education:
    enable: true
    items:
      - title: "Master of Engineering in Computer Science"
        school:
          name: "Virginia Tech"
        date: "August 2024 - Hiatus"
        GPA: "3.56/4.0"
        content: "Currently switching programs to focus on applied data science and computational methods."
      
      - title: "Bachelor of Science in Computational Modeling and Data Analytics"
        school:
          name: "Virginia Tech College of Science"
        date: "August 2020 - May 2024"
        GPA: "3.55/4.0"
        minors: "Computer Science, English, Mathematics, and Statistics"

  achievements:
    enable: true
    items:
      - title: "C.S.C Database Specialist Certificate"
        content: "Issued by Northern Virginia Community College in May 2020."
      - title: "Virginia Tech Honors"
        content: "Received for academic excellence in data analysis and software development."
      - title: "1st place VT Data Analytics Competition"
        content: "Competed and won a data analytics and visualization competition 1st out of 11 teams. (Fall 2021)"
      - title: "2nd place Data Analytics Competition hosted by the American Statistical Association"
        content: "Competed and won second place out of 13 teams. (Spring 2022)"


  projects:
    enable: true
    items:
      - title: "Full Stack Music Diary Web Application"
        content: "A web app with a Postgres database and user authentication built with Typescript, React, Flask, and more."
        image: /images/projects/musicdiarygif.gif
        featured:
          name: Video Demo
          url: "https://drive.google.com/file/d/1FWr1ilmk7lJ2R4PtnLr1vGn9sY9sQqOr/view?usp=sharing"
        badges:
          - "Typescript"
          - "React"
          - "Flask"
          - "Postgres"
          - "SQL"
          - "Python"
        links:
          - icon: fab fa-github
            url: "https://github.com/MusicDiaryDB"
      
      - title: "Observing Macroplastic Pollution Capstone Project"
        content: "In Partnership with The Ocean Conservancy and NOAA Conducted a comprehensive assessment of macroplastic pollution along the United States' coastlines, utilizing ArcGIS for modeling purposes"
        image: /images/projects/conservancy.gif
        featured:
          name: Full Report
          link: "https://docs.google.com/document/d/1tu6tm5eOAAxaqQaO-LOJxwuZX4fOyoS2/edit?usp=sharing&ouid=118387298577732667332&rtpof=true&sd=true"
        badges:
          - "ArcGIS"
          - "Python"
          - "Technical Writing"
          - "Enviromental Data Science"

      - title: "CUDA Programming within GPU Databases"
        content: "Optimized search algorithms for large-scale GPU projects including Conway's Game of Life."
        image: /images/projects/cudaproject.gif
        featured:
          name: Full Paper
          link: "https://drive.google.com/file/d/1YSDyHxcj_0gWQTHmLy4T0r-njAJ8mowV/view?usp=sharing"
        badges:
          - "CUDA"
          - "GPU"
          - "SQL"
          - "C Programming"
        links:
          - icon: fab fa-github
            url: "https://github.com/benzeitlin/cuda-project"

      - title: "RShiny Interactive Dashboard and Statistical Report Generation"
        content: "Worked with the American Statistical Association to help create regression plots to analyze health data using advanced R and Python techniques. Modernized an outdated SAS application and developed an R Shiny app for generating chapter reports efficiently."
        image: /images/projects/RShinyApp.png
        featured:
          name: American Statistical Association Website
          link: "https://www.amstat.org"
        badges:
          - "RShiny"
          - "SAS"
          - "R Programming"

      - title: "Jeopardy: The State of Triple Stumpers"
        content: "Created an academic paper on the pracitce of Jeopardy! questions that no opponents could answer. Helped proved Jeopardy! isn't rigged against existing champions. Statistical Report."
        image: /images/projects/jeopardy.png
        featured:
          name: Full Report
          link: "https://drive.google.com/file/d/1v2qEmYNT82xsuvl60Zinr_PbXdHQaVCE/view?usp=sharing"
        badges:
          - "R Programming"
          - "Dplyr"
          - "Tidyverse"
          - "LaTex"

      - title: "Airbnb Interactive Data Visualization Application"
        content: "Produced an interactive data visualization application to map out airbnbs in five major cities in the US including New York City, Los Angeles, etc."
        image: /images/projects/airbnb.png
        featured:
          name: Full Report
          link: "https://drive.google.com/file/d/14KVgQdrURpwPl5IgsDNbi7fveeEs8gkp/view?usp=sharing"
        badges:
          - "Python"
          - "Pandas"
        
  contact:
    enable: true
    content: "My email inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!"
    btnName: "Email me"
    btnLink: "mailto:benzeitlin1010@gmail.com"

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: "Recent Posts"
    #   enable: true
    socialNetworks:
      github: "https://github.com/benjaminzeitlin1010"
      linkedin: "https://www.linkedin.com/in/benjamin-zeitlin-81856a22a/"

  listPages:
    disableFeaturedImage: false

  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
